# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiJV7cJBCS5kOS-hQNSJdA4I2313ZQYl
"""

import math
import random
import time


# =====================================================================
# PROBLEM 1: AI-Powered Emergency Medical Drones in Dynamic Flood Zones
# Algorithms: Greedy Best-First Search (GBFS), A*, D* Lite Simulation
# =====================================================================
def run_problem_1():
    print("\n" + "=" * 70)
    print(" PROBLEM 1: EMERGENCY MEDICAL DRONE ROUTE OPTIMIZATION")
    print("=" * 70)

    # Grid Map Representation (0: Clear, 1: Obstacle/Swollen River, 2: High Wind/Risk)
    grid = [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 2, 0, 1, 0],
        [1, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 2, 2, 1, 0],
        [0, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
    ]
    start = (0, 0)
    goal = (6, 6)

    def heuristic(p1, p2):
        # Euclidean Straight-line Distance Heuristic
        return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)

    def get_neighbors(pos):
        neighbors = []
        for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nx, ny = pos[0] + dx, pos[1] + dy
            if 0 <= nx < len(grid) and 0 <= ny < len(grid[0]):
                if grid[nx][ny] != 1:  # Not a blocked path
                    # Risk/Weather cost adjustment
                    cost = 3.0 if grid[nx][ny] == 2 else 1.0
                    neighbors.append(((nx, ny), cost))
        return neighbors

    # 1. Greedy Best-First Search
    def gbfs():
        open_list = [(heuristic(start, goal), start)]
        came_from = {}
        visited = set([start])

        while open_list:
            open_list.sort(key=lambda x: x[0])
            _, curr = open_list.pop(0)

            if curr == goal:
                path = [curr]
                while curr in came_from:
                    curr = came_from[curr]
                    path.append(curr)
                return path[::-1]

            for neighbor, _ in get_neighbors(curr):
                if neighbor not in visited:
                    visited.add(neighbor)
                    came_from[neighbor] = curr
                    open_list.append((heuristic(neighbor, goal), neighbor))
        return None

    # 2. A* Search
    def a_star():
        open_list = [(heuristic(start, goal), 0, start)]
        came_from = {}
        g_score = {start: 0}

        while open_list:
            open_list.sort(key=lambda x: x[0])
            f, g, curr = open_list.pop(0)

            if curr == goal:
                path = [curr]
                while curr in came_from:
                    curr = came_from[curr]
                    path.append(curr)
                return path[::-1], g_score[goal]

            for neighbor, cost in get_neighbors(curr):
                tentative_g = g_score[curr] + cost
                if neighbor not in g_score or tentative_g < g_score[neighbor]:
                    g_score[neighbor] = tentative_g
                    came_from[neighbor] = curr
                    f_score = tentative_g + heuristic(neighbor, goal)
                    open_list.append((f_score, tentative_g, neighbor))
        return None, float("inf")

    path_gbfs = gbfs()
    path_astar, cost_astar = a_star()

    print(f"-> Greedy Best-First Path: {path_gbfs}")
    print(
        f"-> A* Optimal Path:        {path_astar} | Total Cost (g): {cost_astar}"
    )
    print("\n[Recommendation]: D* Lite / LPA* for incremental dynamic replanning when paths freeze.")


# =====================================================================
# PROBLEM 2: Smart City Traffic Signal Optimization
# Algorithms: Hill Climbing, Simulated Annealing, Genetic Algorithm
# =====================================================================
def run_problem_2():
    print("\n" + "=" * 70)
    print(" PROBLEM 2: SMART CITY TRAFFIC SIGNAL TIMING OPTIMIZATION")
    print("=" * 70)

    num_signals = 5

    def traffic_cost(timings):
        # Objective: Minimize total delay and fuel loss
        # Mock non-linear objective with local minima
        total_delay = 0
        for i, t in enumerate(timings):
            total_delay += (t - 30) ** 2 + 10 * math.sin(t)
        return round(total_delay, 2)

    # 1. Simple Hill Climbing
    def hill_climbing():
        current = [random.randint(10, 60) for _ in range(num_signals)]
        current_cost = traffic_cost(current)

        for _ in range(100):
            neighbor = list(current)
            idx = random.randint(0, num_signals - 1)
            neighbor[idx] += random.choice([-5, 5])
            neighbor[idx] = max(10, min(60, neighbor[idx]))

            neighbor_cost = traffic_cost(neighbor)
            if neighbor_cost < current_cost:
                current = neighbor
                current_cost = neighbor_cost
            else:
                break  # Stuck at local minimum
        return current, current_cost

    # 2. Simulated Annealing
    def simulated_annealing():
        current = [random.randint(10, 60) for _ in range(num_signals)]
        current_cost = traffic_cost(current)
        T = 100.0
        alpha = 0.95

        while T > 0.1:
            neighbor = list(current)
            idx = random.randint(0, num_signals - 1)
            neighbor[idx] += random.choice([-5, 5])
            neighbor[idx] = max(10, min(60, neighbor[idx]))

            neighbor_cost = traffic_cost(neighbor)
            delta = neighbor_cost - current_cost

            if delta < 0 or random.random() < math.exp(-delta / T):
                current = neighbor
                current_cost = neighbor_cost

            T *= alpha
        return current, current_cost

    hc_sol, hc_cost = hill_climbing()
    sa_sol, sa_cost = simulated_annealing()

    print(f"-> Hill Climbing Result:      Timings={hc_sol} | Congestion Cost={hc_cost}")
    print(f"-> Simulated Annealing Result: Timings={sa_sol} | Congestion Cost={sa_cost}")
    print("\n[Recommendation]: GA/Memetic Parallel Search to optimize multi-objective traffic corridors.")


# =====================================================================
# PROBLEM 3: Autonomous Mars Rover Navigation
# Algorithm: Online Search (Learning Real-Time A* - LRTA* Simulation)
# =====================================================================
def run_problem_3():
    print("\n" + "=" * 70)
    print(" PROBLEM 3: AUTONOMOUS MARS ROVER ONLINE NAVIGATION (LRTA*)")
    print("=" * 70)

    # Environment unknown ahead of time
    grid_size = 5
    goal = (4, 4)

    # Heuristic table H initialized to straight line distances
    H = {
        (x, y): math.sqrt((4 - x) ** 2 + (4 - y) ** 2)
        for x in range(grid_size)
        for y in range(grid_size)
    }

    # Obstacles detected dynamically on arrival
    dynamic_obstacles = {(1, 1), (1, 2), (2, 2), (3, 1)}

    current = (0, 0)
    path = [current]

    print(f"Starting LRTA* Rover Execution from {current} to {goal}...")

    steps = 0
    while current != goal and steps < 20:
        steps += 1
        # Look at valid neighbors
        neighbors = []
        for dx, dy in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nx, ny = current[0] + dx, current[1] + dy
            if (
                0 <= nx < grid_size
                and 0 <= ny < grid_size
                and (nx, ny) not in dynamic_obstacles
            ):
                neighbors.append((nx, ny))

        if not neighbors:
            print("-> Rover Trapped!")
            break

        # Select neighbor with min (cost + H(s'))
        best_neighbor = min(neighbors, key=lambda s: 1 + H[s])

        # Update heuristic of current state
        H[current] = 1 + H[best_neighbor]

        # Execute step online
        current = best_neighbor
        path.append(current)

    print(f"-> Online Exploration Path Executed: {path}")
    print("\n[Recommendation]: LRTA* + EKF-SLAM for real-time dynamic obstacle avoidance on Mars.")


# =====================================================================
# PROBLEM 4: Automated University Exam Timetabling (CSP)
# Algorithms: Backtracking with Forward Checking & MRV Heuristic
# =====================================================================
def run_problem_4():
    print("\n" + "=" * 70)
    print(" PROBLEM 4: AUTOMATED EXAM TIMETABLING (CSP)")
    print("=" * 70)

    exams = ["CS101", "CS102", "MA101", "PH101"]
    time_slots = ["Mon_AM", "Mon_PM", "Tue_AM"]

    # Hard Constraints: Overlapping students cannot take exams at the same time
    conflicts = {
        "CS101": ["CS102", "MA101"],
        "CS102": ["CS101", "PH101"],
        "MA101": ["CS101", "PH101"],
        "PH101": ["CS102", "MA101"],
    }

    assignment = {}

    def is_consistent(exam, slot):
        for neighbor in conflicts[exam]:
            if neighbor in assignment and assignment[neighbor] == slot:
                return False
        return True

    def backtrack_csp():
        if len(assignment) == len(exams):
            return True

        # MRV Heuristic: Pick unassigned exam with fewest legal choices
        unassigned = [e for e in exams if e not in assignment]
        unassigned.sort(
            key=lambda e: sum(1 for s in time_slots if is_consistent(e, s))
        )
        exam = unassigned[0]

        for slot in time_slots:
            if is_consistent(exam, slot):
                assignment[exam] = slot
                if backtrack_csp():
                    return True
                del assignment[exam]
        return False

    if backtrack_csp():
        print("-> Valid Timetable Schedule Generated Successfully (No Overlaps):")
        for exam, slot in assignment.items():
            print(f"   * {exam} --> {slot}")
    else:
        print("-> No valid timetable configuration found under given constraints.")

    print("\n[Recommendation]: Hybrid Backtracking (AC-3 + MRV) combined with Genetic Local Search.")


# =====================================================================
# PROBLEM 5: Strategic Real-Time Game AI (Minimax & Alpha-Beta)
# Algorithms: Minimax, Alpha-Beta Pruning Simulation
# =====================================================================
def run_problem_5():
    print("\n" + "=" * 70)
    print(" PROBLEM 5: REAL-TIME STRATEGY GAME AI (ALPHA-BETA PRUNING)")
    print("=" * 70)

    # Simulated Game Tree Terminal Leaf Evaluation Scores
    leaf_nodes = [3, 5, 6, 9, 1, 2, 0, -1]
    print(f"Evaluation Scores at Game Tree Depth 3: {leaf_nodes}")

    pruned_branches = 0

    def alpha_beta(depth, node_index, is_max, alpha, beta):
        nonlocal pruned_branches

        if depth == 3:
            return leaf_nodes[node_index]

        if is_max:
            max_eval = -math.inf
            for i in range(2):
                val = alpha_beta(
                    depth + 1, node_index * 2 + i, False, alpha, beta
                )
                max_eval = max(max_eval, val)
                alpha = max(alpha, val)
                if beta <= alpha:
                    pruned_branches += 1
                    break  # Beta Cutoff
            return max_eval
        else:
            min_eval = math.inf
            for i in range(2):
                val = alpha_beta(
                    depth + 1, node_index * 2 + i, True, alpha, beta
                )
                min_eval = min(min_eval, val)
                beta = min(beta, val)
                if beta <= alpha:
                    pruned_branches += 1
                    break  # Alpha Cutoff
            return min_eval

    optimal_val = alpha_beta(0, 0, True, -math.inf, math.inf)

    print(f"-> Minimax Optimal Value for AI: {optimal_val}")
    print(f"-> Number of Pruned Subtrees:    {pruned_branches}")
    print("\n[Recommendation]: Iterative Deepening Minimax + Transposition Tables for Real-Time Budgets.")


# =====================================================================
# MAIN MENU INTERFACE
# =====================================================================
def main():
    while True:
        print("\n" + "=" * 70)
        print(" ARTIFICIAL INTELLIGENCE - ASSIGNMENT SOLUTION SUITE")
        print("=" * 70)
        print(" 1. Problem 1: AI Emergency Medical Drones (Search in Dynamic Environment)")
        print(" 2. Problem 2: Smart City Traffic Signal Optimization (Local Search)")
        print(" 3. Problem 3: Autonomous Mars Rover (Online Navigation)")
        print(" 4. Problem 4: Automated Exam Timetabling (CSP)")
        print(" 5. Problem 5: RTS Game AI Opponent (Minimax & Alpha-Beta)")
        print(" 6. Run ALL Simulations")
        print(" 0. Exit")
        print("=" * 70)

        choice = input("Enter your choice (0-6): ").strip()

        if choice == "1":
            run_problem_1()
        elif choice == "2":
            run_problem_2()
        elif choice == "3":
            run_problem_3()
        elif choice == "4":
            run_problem_4()
        elif choice == "5":
            run_problem_5()
        elif choice == "6":
            run_problem_1()
            run_problem_2()
            run_problem_3()
            run_problem_4()
            run_problem_5()
        elif choice == "0":
            print("\nExiting solution suite. Goodbye!")
            break
        else:
            print("\n[!] Invalid Selection. Please pick a choice between 0 and 6.")

        input("\nPress ENTER to return to the selection menu...")


if __name__ == "__main__":
    main()